# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171109_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='posicion_cargo',
            new_name='posicion_o_cargo',
        ),
    ]
