# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app.core', '0003_auto_20171109_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='fin_contrato',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='inicio_contrato',
        ),
    ]
