# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171109_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cuit',
            new_name='CUIT',
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Rubro'),
            preserve_default=False,
        ),
    ]
