# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171117_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Rubro'),
        ),
    ]
